package com.redhat.bpms.examples.mortgage;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Property implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PROPERTY_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "PROPERTY_ID_SEQ", name = "PROPERTY_ID_GENERATOR")
   private Long id;

   @org.kie.api.definition.type.Label(value = "Property Address")
   private String address;

   @org.kie.api.definition.type.Label(value = "Sale Price")
   private Integer price;

   public Property()
   {
   }

   public Long getId()
   {
      return this.id;
   }

   public void setId(Long id)
   {
      this.id = id;
   }

   public String getAddress()
   {
      return this.address;
   }

   public void setAddress(String address)
   {
      this.address = address;
   }

   public Integer getPrice()
   {
      return this.price;
   }

   public void setPrice(Integer price)
   {
      this.price = price;
   }

   public Property(Long id, String address,
                   Integer price)
   {
      this.id = id;
      this.address = address;
      this.price = price;
   }

}