package com.redhat.bpms.examples.mortgage;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ValidationError implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Cause of Error")
   private String cause;

   public ValidationError()
   {
   }

   public String getCause()
   {
      return this.cause;
   }

   public void setCause(String cause)
   {
      this.cause = cause;
   }

   public ValidationError(String cause)
   {
      this.cause = cause;
   }

}