package com.redhat.bpms.examples.mortgage;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Appraisal implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "APPRAISAL_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "APPRAISAL_ID_SEQ", name = "APPRAISAL_ID_GENERATOR")
   private Long id;

   @javax.persistence.ManyToOne(cascade = { javax.persistence.CascadeType.ALL }, fetch = javax.persistence.FetchType.EAGER)
   @org.kie.api.definition.type.Label(value = "Appraised Property")
   private com.redhat.bpms.examples.mortgage.Property property;

   @org.kie.api.definition.type.Label(value = "Appraisal Date")
   private java.util.Date date;

   @org.kie.api.definition.type.Label(value = "Appraised Value")
   private Integer value;

   public Appraisal()
   {
   }

   public Long getId()
   {
      return this.id;
   }

   public void setId(Long id)
   {
      this.id = id;
   }

   public com.redhat.bpms.examples.mortgage.Property getProperty()
   {
      return this.property;
   }

   public void setProperty(com.redhat.bpms.examples.mortgage.Property property)
   {
      this.property = property;
   }

   public java.util.Date getDate()
   {
      return this.date;
   }

   public void setDate(java.util.Date date)
   {
      this.date = date;
   }

   public Integer getValue()
   {
      return this.value;
   }

   public void setValue(Integer value)
   {
      this.value = value;
   }

   public Appraisal(Long id,
         com.redhat.bpms.examples.mortgage.Property property,
         java.util.Date date, Integer value)
   {
      this.id = id;
      this.property = property;
      this.date = date;
      this.value = value;
   }

}